Ketchup ganttchart implemention
smeup/ketchup pull request #1743
Opened 2023-10-18 04:31 UTC by dev01prishusoft

2023-10-18 09:24 UTC, lucafoscili requested changes
In addition to the comments, please remove commented lines of code (I don't mean real comments, but old lines removed with //).

2023-10-18 09:24 UTC, lucafoscili commented on packages/ketchup/src/components/kup-planner/utils/kup-grid-renderer/kup-grid-renderer.tsx
> +export class KupGirdRenderer {
Typo - Gird should be Grid

2023-10-18 09:24 UTC, lucafoscili commented on packages/ketchup/src/components/kup-planner/utils/kup-planner-renderer.data.ts
> +const mainGanttPlaner1Items: any = [
Typo - Planer should be Planner

2023-10-18 09:24 UTC, lucafoscili commented on packages/ketchup/src/components/kup-planner/utils/kup-planner-renderer.data.ts
This file is used for mock ups, it shouldn't be inside the component but included in the testing page (planner.html + assets/planner.js)

2023-10-20 06:50 UTC, dev01prishusoft commented on .yarn/install-state.gz
Fix and Pushed

2023-12-11 08:31 UTC, lucafoscili approved these changes

2023-12-11 08:36 UTC, merged