Feat / kup-typography
smeup/ketchup pull request #2021
Opened 2024-08-13 15:18 UTC by Leonardo-Signorelli

2024-08-19 11:34 UTC, pasere-smeup requested changes
Added some comments into the code, please check.

Showcase example is missing.

2024-08-19 11:34 UTC, pasere-smeup commented on packages/ketchup/src/f-components/f-typography/f-typography.tsx
> +    if (!props.toolbar) {
props.toolbar si boolean; set to false is different than not set, but here will go into the if if undefined OR false

2024-08-19 11:34 UTC, pasere-smeup commented on packages/ketchup/src/typography.html
> +<!DOCTYPE html>
this example doesn't work!

2024-09-11 14:50 UTC, Leonardo-Signorelli commented on packages/ketchup/src/components/kup-tab-bar/kup-tab-bar-declarations.ts
> -    value?: string;
I have already removed this Event as Toolbar events are now isolated inside the toolbar declarations and re-called inside components

2024-09-11 15:00 UTC, Leonardo-Signorelli commented on packages/ketchup/src/components/kup-typography/kup-typography.tsx
> +        eventName: 'kup-typography-icon-click',
Fixed

2024-09-11 15:37 UTC, pasere-smeup approved these changes
ok

2024-09-11 15:39 UTC, merged