Fix: Box Vertical Dimension
smeup/ketchup pull request #2308
Opened 2024-12-16 13:14 UTC by EmanueleCitarella

Removed vertical dimension management for box component

2024-12-17 10:16 UTC, Leonardo-Signorelli requested changes

2024-12-17 10:31 UTC, EmanueleCitarella commented on packages/ketchup/src/components/kup-box/kup-box.tsx
> -            sectionStyle.flex = `0 0 ${section.dim}`;
if not removed, it overrides the flex property from scss classes that set flex to a '0 0 auto' and layout still breaks.  
Instead, the result with flex is still the same.
If it's a scheda error, then I'll restore the flex style for section.
![Screenshot 2024-12-17 at 11 29 54](https://github.com/user-attachments/assets/5842ed3f-4722-45c3-8d91-39b7eb9a888f)

2024-12-17 11:39 UTC, Leonardo-Signorelli commented on packages/ketchup/src/components/kup-box/kup-box.tsx
> -            sectionStyle.flex = `0 0 ${section.dim}`;
It's not a scheda error. You have to remove the flex logic only for the vertical layout. With your fix you'll remove it also from the horizontal layout ( is still working on your browser cause there's stille the max-width but it's not fully correct )

2024-12-17 11:54 UTC, EmanueleCitarella commented on packages/ketchup/src/components/kup-box/kup-box.tsx
> -            sectionStyle.flex = `0 0 ${section.dim}`;
Understood, I moved the flex logic in the horizontal condition, I think it's the right choice and testing it, it seems that works correctly!

2024-12-18 08:40 UTC, Leonardo-Signorelli approved these changes

2024-12-18 08:41 UTC, merged